In [1]:
import numpy as np

In [4]:
multi_dim_array = np.random.rand(100,4)

In [5]:
multi_dim_array

array([[0.83442323, 0.26600324, 0.58008429, 0.33481007],
       [0.11597426, 0.11167115, 0.26568934, 0.11135508],
       [0.98925814, 0.10633758, 0.96446623, 0.73456273],
       [0.09940729, 0.68193808, 0.07285016, 0.13702712],
       [0.97891122, 0.23007923, 0.18163227, 0.69933594],
       [0.73703147, 0.77376068, 0.42144888, 0.47703864],
       [0.34216082, 0.51238663, 0.26027553, 0.80506182],
       [0.88669149, 0.21500779, 0.96000093, 0.37932901],
       [0.27635899, 0.07590469, 0.54518705, 0.00421557],
       [0.74356354, 0.68155551, 0.12650768, 0.99178614],
       [0.62661956, 0.67818427, 0.22382488, 0.42140554],
       [0.10622448, 0.73608011, 0.48134435, 0.77934834],
       [0.0396257 , 0.85254495, 0.09161339, 0.3462991 ],
       [0.56978067, 0.12040863, 0.36080408, 0.11005695],
       [0.86381433, 0.20683844, 0.21844572, 0.80230374],
       [0.76387394, 0.00811006, 0.41115004, 0.82142996],
       [0.8174317 , 0.41090731, 0.4774975 , 0.82793039],
       [0.5937498 , 0.33716628,

In [6]:
first_column = multi_dim_array[:,0]

In [7]:
np.mean(first_column)

0.5394512808017324

In [11]:
np.where(multi_dim_array>0.5)

(array([ 0,  0,  2,  2,  2,  3,  4,  4,  5,  5,  6,  6,  7,  7,  8,  9,  9,
         9, 10, 10, 11, 11, 12, 13, 14, 14, 15, 15, 16, 16, 17, 17, 17, 18,
        18, 18, 18, 19, 19, 19, 20, 20, 21, 21, 22, 23, 24, 25, 26, 26, 27,
        27, 28, 29, 29, 29, 30, 30, 30, 31, 31, 31, 31, 32, 32, 32, 33, 33,
        34, 34, 34, 35, 35, 35, 36, 36, 37, 37, 38, 38, 38, 38, 39, 39, 40,
        40, 41, 42, 42, 43, 43, 43, 43, 45, 45, 45, 46, 47, 47, 47, 48, 49,
        49, 50, 51, 51, 51, 51, 52, 53, 54, 54, 55, 55, 55, 56, 56, 57, 57,
        58, 58, 58, 59, 59, 60, 60, 61, 62, 62, 63, 63, 64, 65, 65, 65, 66,
        66, 67, 67, 67, 68, 68, 69, 69, 69, 70, 70, 71, 71, 72, 73, 73, 73,
        74, 74, 75, 75, 75, 75, 76, 76, 77, 77, 78, 78, 78, 79, 79, 79, 80,
        80, 80, 81, 81, 82, 82, 82, 83, 84, 84, 84, 85, 85, 86, 86, 87, 88,
        88, 89, 89, 91, 91, 92, 92, 93, 93, 93, 94, 95, 95, 95, 96, 96, 97,
        97, 97, 98, 98, 99, 99, 99]),
 array([0, 2, 0, 2, 3, 1, 0, 3, 0, 1, 1, 3, 0, 2, 

In [12]:
multi_dim_array[np.where(multi_dim_array>0.5)]

array([0.83442323, 0.58008429, 0.98925814, 0.96446623, 0.73456273,
       0.68193808, 0.97891122, 0.69933594, 0.73703147, 0.77376068,
       0.51238663, 0.80506182, 0.88669149, 0.96000093, 0.54518705,
       0.74356354, 0.68155551, 0.99178614, 0.62661956, 0.67818427,
       0.73608011, 0.77934834, 0.85254495, 0.56978067, 0.86381433,
       0.80230374, 0.76387394, 0.82142996, 0.8174317 , 0.82793039,
       0.5937498 , 0.81380938, 0.74383908, 0.53191212, 0.7899802 ,
       0.64632312, 0.55715062, 0.79140799, 0.82104932, 0.94682874,
       0.93558611, 0.54714652, 0.88010698, 0.82410201, 0.81261492,
       0.8783675 , 0.72034285, 0.52290018, 0.66763742, 0.56756938,
       0.61754648, 0.59877478, 0.8190539 , 0.95742932, 0.90967828,
       0.8278753 , 0.60053278, 0.51664104, 0.94536684, 0.89755759,
       0.68460972, 0.87003938, 0.90970173, 0.55905002, 0.99333204,
       0.67359403, 0.98388311, 0.67063732, 0.69515776, 0.54149272,
       0.81311489, 0.81621711, 0.63903105, 0.59165253, 0.91806