# Filtering data

Manaully selecting data from an array by giving indices or ranges works if you want contiguous chunks of data, but sometimes you want to be able to grab arbitrary data from an array.

Let's explore the options for more advanced indexing of arrays.

In [23]:
import numpy as np

We'll use the following array in our examples. To make it easier to understand what's going on, the value of the digit after the decimal place is set to match the index (i.e. the value at index <u>3</u> is 10.<u>3</u>):

a = np.array([6.0, 2.1, 8.2, 10.3, 5.4, 1.5, 7.6, 3.7, 9.8])

## Select by index

We've already seen that you can access a single element by giving its index:

In [24]:
a = np.array([6.0, 2.1, 8.2, 10.3, 5.4, 1.5, 7.6, 3.7, 9.8])

In [25]:
a[5]

np.float64(1.5)

and that we can also pass a slice (just like in a Python list):

In [26]:
a[5:7]

array([1.5, 7.6])

To start to get more advanced than what Python lists support, we can also provide a list of element indices that we want. So, if we want elements `5` and `6` then we can pass in a list of those indices:

In [27]:
wanted_elements = [5, 6]

a[wanted_elements]

array([1.5, 7.6])

So this gave us back the item at index `5` an the item at index `6`.

The indices we pass in do not have to be contiguous, they can be from anywhere in the array:

In [28]:
wanted_elements = [4, 7]
a[wanted_elements]

array([5.4, 3.7])

They can be in any order:

In [29]:
wanted_elements = [7, 4]
a[wanted_elements]

array([3.7, 5.4])

And we can even repeat them and the matching value is repeated in the output:

In [30]:
wanted_elements = [4, 4, 7, 4]
a[wanted_elements]

array([5.4, 5.4, 3.7, 5.4])

In all these cases we have made a separate variable to hold the indices and then passed in that variable. We can do this in one step too:

In [31]:
a[[4, 4, 7, 4]]

array([5.4, 5.4, 3.7, 5.4])

The outer `[]` are the "index the array `a`" syntax, and the inner `[]` are the "make a list of these numbers" syntax.

### Exercise #

Using this indexing syntax, extract the following results:

1. `[6.  8.2 5.4 7.6 9.8]`
2. `[ 6.   2.1  8.2 10.3]`
3. `[9.8 1.5 3.7 5.4]`


In [32]:
a = np.array([6.0, 2.1, 8.2, 10.3, 5.4, 1.5, 7.6, 3.7, 9.8])

In [33]:
a[[0, 2, 4, 6, 8]]

array([6. , 8.2, 5.4, 7.6, 9.8])

In [34]:
a[[0, 1, 2, 3]]

array([ 6. ,  2.1,  8.2, 10.3])

In [35]:
a[[8, 5, 7, 4]]

array([9.8, 1.5, 3.7, 5.4])

## Filter by boolean

Let's say that we want all the values in the array that are larger than 4.0. We could do this by manually finding all those indices which match and constructing a list of them to use as a selector:

In [36]:
a

array([ 6. ,  2.1,  8.2, 10.3,  5.4,  1.5,  7.6,  3.7,  9.8])

Or, we can use a list of boolean values, where we set those elements we want to extract to `True` and those we want to be rid of to `False`:

In [37]:
large_indices = [0, 2, 3, 4, 6, 8]
a[large_indices]

array([ 6. ,  8.2, 10.3,  5.4,  7.6,  9.8])

In [38]:
mask = [True, False, True, True, True, False, True, False, True]

a[mask]

array([ 6. ,  8.2, 10.3,  5.4,  7.6,  9.8])

These lists of `True` and `False` are referred to as *boolean arrays*.

With a larger array it would be tedious to create this list by hand. Luckily NumPy provides us with a way of constructing these automatically. If we want a boolean array matching the values which are greater than 4, we can use the same sort of syntax we used for multiplication, but use `>` instead:

In [39]:
a > 4

array([ True, False,  True,  True,  True, False,  True, False,  True])

This mask can be saved to a variable and passed in as an index:

In [40]:
mask = a > 4

a[mask]

array([ 6. ,  8.2, 10.3,  5.4,  7.6,  9.8])

Or, in one line:

In [41]:
a[ a > 4]

array([ 6. ,  8.2, 10.3,  5.4,  7.6,  9.8])

which can be read as "select from `a` the elements where `a` is greater than 4"

### Exercise #

Extract all the values in `a` which are:
1. Less than 5
2. Greater than or equal to 8.2
3. Equal to 6.0



In [42]:
a[a<5]


array([2.1, 1.5, 3.7])

In [43]:
a[a>=8.2]

array([ 8.2, 10.3,  9.8])

In [44]:
a[a==6.0]

array([6.])

## Setting from filters

Just like at the beginning of the course when we set values in an array with:
```python
a[4] = 99.4
```

We can also use the return value of any filter to set values. For example, if we wanted to set all values greater than 4 to be 0 we can do:

In [45]:
a

array([ 6. ,  2.1,  8.2, 10.3,  5.4,  1.5,  7.6,  3.7,  9.8])

In [47]:
a[a>4] = 0

In [48]:
a

array([0. , 2.1, 0. , 0. , 0. , 1.5, 0. , 3.7, 0. ])

## Filtering multi-dimensional data

In [49]:
grid = np.array([[1, 2, 3], [4, 5, 6,], [7, 8, 9]])
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [50]:
grid.shape

(3, 3)

In [52]:
grid[grid>4]

array([5, 6, 7, 8, 9])

In this case, it has lost the information about *where* the numbers have come from. The dimensionality has been lost.

NumPy hasn't much choice in this case, as if it were to return the result with the same shape as the original array `grid`, what should it put in the spaces that we've filtered out?

```
[[? ? ?]
 [? 5 6]
 [7 8 9]]
```

You might think that it could fill those with `0`, or `-1` but any of those could very easily cause a problem with code that follows. NumPy doesn't take a stance on this as it would be dangerous.

In your code, you know what you're doing with your data, so it's ok for you to decide on a case-by-case basis. If you decide that you want to keep the original shape, but replace any filtered-out values with a `0` then you can use NumPy's [`where`](https://numpy.org/doc/stable/reference/generated/numpy.where.html) function. It takes three arguments:
1. the boolean array selecting the values,
2. an array or values to use in the spots you're keeping, and
3. an array or values to use in the spots you're filtering out.

So, in the case where we want to replace any values less-than or equal-to 4 with `0`, we can use:

In [53]:
np.where(grid>4)

(array([1, 1, 2, 2, 2]), array([1, 2, 0, 1, 2]))

In [54]:
grid[np.where(grid>4)]

array([5, 6, 7, 8, 9])

In [60]:
np.where(grid > 4, grid, 0)

array([[0, 0, 0],
       [0, 5, 6],
       [7, 8, 9]])

Note that this has not affected the original array:

In [58]:
grid

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

One final way that you can reduce your data, while keeping the dimensionality is to use [masked arrays](https://numpy.org/doc/stable/reference/maskedarray.html). This is useful in situations here you have *missing data*. The advantage of masked arrays is that operations like averaging are not affected by the cells that are masked out. The downside is that for much larger arrays they will use more memory and can be slower to operate on.

In [59]:
masked_grid = np.ma.masked_array(grid, grid <=4)
print(masked_grid)

[[-- -- --]
 [-- 5 6]
 [7 8 9]]


In [61]:
np.mean(np.where(grid>4, grid, 0))

np.float64(3.888888888888889)

In [62]:
np.mean(masked_grid)

np.float64(7.0)

### Exercise #

The `rain` data set represents the prediction of metres of rainfall in an area and is based on the data from [ECMWF](https://apps.ecmwf.int/codes/grib/param-db/?id=228). It is two-dimensional with axes of latitude and longitude.

```python
with np.load("weather_data.npz") as weather:
    rain = weather["rain"]
    uk_mask = weather["uk"]
    irl_mask = weather["ireland"]
    spain_mask = weather["spain"]
```

- Calculate the mean of the entire 2D `rain` data set.
- Look at the `uk_mask` array, including its `dtype` and `shape`
- Filter the `rain` data set to contain only those values from within the UK.
  - Does `[]` indexing, `np.where` or `masked_arrays` make the most sense for this task?
- Calculate the mean (and maximum and minimum if you like) of the data


In [63]:
with np.load("weather_data.npz") as weather:
    rain = weather["rain"]

    uk_mask = weather['uk']
    irl_mask = weather['ireland']
    spain_mask = weather['spain']

In [64]:
rain

array([[3.38745117e-03, 1.99127197e-03, 3.33404541e-03, ...,
        3.05938721e-03, 3.66210938e-03, 4.50134277e-03],
       [5.26428223e-04, 1.67846680e-03, 3.41033936e-03, ...,
        3.79180908e-03, 2.51007080e-03, 1.67083740e-03],
       [2.93731689e-03, 1.54113770e-03, 1.51824951e-03, ...,
        3.08990479e-03, 4.05120850e-03, 4.04357910e-03],
       ...,
       [9.91821289e-05, 1.52587891e-04, 1.52587891e-04, ...,
        2.28881836e-05, 6.86645508e-05, 1.14440918e-04],
       [1.67846680e-04, 1.22070312e-04, 1.60217285e-04, ...,
        7.62939453e-05, 1.14440918e-04, 6.10351562e-05],
       [2.05993652e-04, 1.44958496e-04, 1.67846680e-04, ...,
        1.37329102e-04, 4.57763672e-05, 2.28881836e-05]], shape=(75, 75))

In [66]:
np.mean(rain)

np.float64(0.003113156467013889)

In [67]:
rain = rain * 1000 #from metres to mm

In [68]:
np.mean(rain)

np.float64(3.113156467013889)

In [69]:
uk_mask.shape

(75, 75)

In [70]:
uk_mask.dtype

dtype('bool')

In [71]:
uk_mask

array([[False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       ...,
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False]], shape=(75, 75))

In [72]:
uk_rain = rain[uk_mask]

In [73]:
np.mean(uk_rain)

np.float64(7.5836526862097005)

In [74]:
np.mean(rain[irl_mask])

np.float64(4.611112633529975)

In [75]:
np.mean(rain[spain_mask])

np.float64(0.8478509374411709)